CREATE TABLE "READER" (
    "ID" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(50),
    "ADDRESS" VARCHAR(100),
    "EMAIL" VARCHAR(50),
    "NOTE" VARCHAR(255)
);

CREATE TABLE "BOOK" (
    "ID" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "TITLE" VARCHAR(100),
    "AUTHOR" VARCHAR(100),
    "PUBLISHED" INT,
    "NOTE" VARCHAR(255)
);

CREATE TABLE "LOAN" (
    "ID" BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "READERID" BIGINT REFERENCES READER(ID) ON DELETE CASCADE,
    "BOOKID" BIGINT REFERENCES BOOK(ID) ON DELETE CASCADE,
    "STARTTIME" DATE,
    "ENDTIME" DATE,
    "REALEND" TIMESTAMP
);